import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import FooterMb from "@/components/FooterMb";
import TelBtn from "@/components/TelBtn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased relative`}>
        <Header></Header>
        {children}
        <TelBtn></TelBtn>
        <Footer></Footer>
        <FooterMb></FooterMb>
      </body>
    </html>
  );
}
